### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by cbruno10** [francois2metz/steampipe-plugin-gandi#1]
Hey @francois2metz , we were excited to see you had started a new plugin for Gandi, and even though we are a bit early, we downloaded it and started playing around with it.

The basic structure and results look good so far. While using the plugin, we did come up with a few suggestions based on our best practices:
- In `docs/index.md`, I think `internet` would be a more suitable category instead of `public cloud`
- In `config/gandi.sp`, any thoughts on renaming the `apikey` param to `key`, like the Terraform provider does (https://registry.terraform.io/providers/psychopenguin/gandi/latest/docs)? There are multiple providers, but all of them seem to use `key`. I'm not sure how Gandi refers to this API key in its own docs or config, but if you wanted to keep the API key name, then a suggestion would be renaming it to `api_key`.
- At https://github.com/francois2metz/steampipe-plugin-gandi/blob/main/.goreleaser.yml#L22, `scalingo` should be updated to `gandi`
- When looking for an environment variable, since [go-gandi](https://github.com/go-gandi/go-gandi/blob/master/cmd/gandi.go#L20) uses `GANDI_KEY`, maybe we should use that too, instead of `GANDI_API_KEY`?
- The `ColumnType_DATETIME` has been deprecated and replaced with `ColumnType_TIMESTAMP` (our docs have some examples that are outdated and still use the deprecated one, so apologies if you were following those)
- Some columns in `gandi_domain` are missing descriptions (not sure if you were planning on adding those later, but figured I'd mention in case not)
- Does the SDK/API support pagination at all?

**Comment by francois2metz** [comment]
Hi @cbruno10.

I finally took the time to handle the last point, and I updated the SDK to handle pagination. I'm working to add some new tables, but an initial release could be made.

**Comment by cbruno10** [comment]
@francois2metz Thanks for making the updates! I had another look at the code while refamiliarizing myself with the plugin and had a few questions/suggestions before initial release:
- Do the domain and forward resource types support a get function at all in the SDK? If so, are we able to add the get function in their table(s)?
- Are there 2-3 more examples you could add into each table doc? For instance, in the domain table, maybe one using the `auto_renew` column or showing all domains owned by a particular owner, and for the mailbox table, showing if a mailbox is close to its quota or not (apologies if I misunderstood any of the columns and used them incorrectly in the suggestions above).
- The basic examples you have are good, but usually we like to provide a few examples for each table so users have a strong starting point to create their own queries.

**Comment by cbruno10** [comment]
@francois2metz Also, I forgot to ask above, do you know what Gandi's brand color is? In the index doc, right now it's #0d0b30, but on their site, their logo looks to be black, or purple on pages like https://news.gandi.net/en/.

**Comment by cbruno10** [comment]
Hey @francois2metz , just checking in, did you have a chance to look at my previous questions above? It seems like some updates were made to the plugin since then, like brand colour updates, but wanted to check if you had any questions as a follow-up, thanks!

**Comment by francois2metz** [comment]
Hi @cbruno10 I did some updates but I send a few feedbacks to Gandi about their documentation and some responses.

**Comment by cbruno10** [comment]
Thanks @francois2metz , the updates look good! From my point of view, this plugin is ready for publishing to the Hub. Can you please create another release and once that's created, I'll push it to the Hub.
